services:
  - type: web
    name: flask-app
    env: python
    region: us-central
    buildCommand: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      rustup default stable
      pip install -r requirements.txt
    startCommand: gunicorn app:app
