services:
  - type: web
    name: flask-app
    env: python
    region: us-central
    buildCommand: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      rustup default stable
      apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python3-dev cargo
      pip install -r requirements.txt
    startCommand: pyhton app.py:app
